In [2]:
import pandas as pd

In [5]:
df=pd.read_csv('titanic.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (4.18.1)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (1.16.0)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (2.12.5)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (2.2.6)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.4.26)
Requirement already satisfied: patsy>=0.5.6 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
!python -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\mahesh yadav\appdata\local\programs\python\python313\lib\site-packages (25.3)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 730.2 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 730.2 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 730.2 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 642.5 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 642.5 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 572.6 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 572.6 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 572.6 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 572.6 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 494.6 kB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 494.6 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 483.4 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 483.4 kB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 499.2 kB/s  0:00:03
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3
Successfully installed pip-26.0.1

In [18]:
from pandas_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

C:\Users\Mahesh Yadav\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\Mahesh Yadav\AppData\Local\Temp\ipykernel_5064\4209343599.py:1: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport
Summarize dataset:  41%|██████████████▍                    | 7/17 [00:00<00:00, 14.46it/s, Describe variable: Embarked]
100%|█████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 195.83it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 47/47 [00:03<00:00, 12.83it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:03<00:00,  3.76s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.43s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.26it/s]

In [20]:
ms=pd.read_csv('tips.csv')

In [21]:
ms.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [23]:
from pandas_profiling import ProfileReport
prof = ProfileReport(ms)
prof.to_file(output_file='tipsoutput.html')

Summarize dataset:  17%|██████▌                                | 2/12 [00:00<00:00, 17.48it/s, Describe variable: size]
100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 179.29it/s]
Summarize dataset: 100%|████████████████████████████████████████████████████| 25/25 [00:02<00:00, 11.85it/s, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.36s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  7.30it/s]
Export report to file: 100%|████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 127.26it/s]